Populate completions with metadata and make completions non exclusive
clojure-emacs/cider pull request #3226
Opened 2022-07-25 15:17 UTC by toniz4

This makes possible to override the cider completion style in `completion-category-defaults` or `completion-category-overrides`.

This will simplify the workarounds needed to make cider work with `orderless` set as the "global" completion style. like seen in https://github.com/clojure-emacs/cider/issues/3019#issuecomment-1024898789. With this pull request, the following will work. 

```elisp
(setq completion-category-defaults '((cider (styles basic)))
```

The code is basicaly the same as the function returned by `completion-table-dynamic`, but simplified since we don't need to check `switch-buffer`, since is always `nil` in this context. And when `(eq action 'metadata)`, return the metadata. 

completion-table-dynamic, in minibuffer.el
```elisp
(defun completion-table-dynamic (fun &optional switch-buffer)
  (lambda (string pred action)
    (if (or (eq (car-safe action) 'boundaries) (eq action 'metadata))
        ;; `fun' is not supposed to return another function but a plain old
        ;; completion table, whose boundaries are always trivial.
        nil
      (with-current-buffer (if (not switch-buffer) (current-buffer)
                             (let ((win (minibuffer-selected-window)))
                               (if (window-live-p win) (window-buffer win)
                                 (current-buffer))))
        (complete-with-action action (funcall fun string) string pred)))))
```
The implementation in the pull request
```elisp
(lambda (string pred action)
              (cond ((eq action 'metadata) `(metadata (category . cider)))
                    ((eq (car-safe action) 'boundaries) nil)
                    (t (with-current-buffer (current-buffer)
                         (complete-with-action action
                                               (cider-complete string) string pred)))))
```

I've been using this implementation for 2 days with `advice-add`, experienced no problems.

Let me know if its needed to add any documentation around this .

-----------------

Before submitting the PR make sure the following things have been done (and denote this
by checking the relevant checkboxes):

- [x] The commits are consistent with our [contribution guidelines](../blob/master/.github/CONTRIBUTING.md)
- [ ] You've added tests (if possible) to cover your change(s)
- [x] All tests are passing (`eldev test`)
- [x] All code passes the linter (`eldev lint`) which is based on [`elisp-lint`](https://github.com/gonewest818/elisp-lint) and includes
  - [byte-compilation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html), [`checkdoc`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Tips.html), [check-declare](https://www.gnu.org/software/emacs/manual/html_node/elisp/Declaring-Functions.html), packaging metadata, indentation, and trailing whitespace checks.
- [ ] You've updated the [changelog](../blob/master/CHANGELOG.md) (if adding/changing user-visible functionality)
- [ ] You've updated the [user manual](../blob/master/doc) (if adding/changing user-visible functionality)

Thanks!

*If you're just starting out to hack on CIDER you might find this [section of its
manual][1] extremely useful.*

[1]: https://docs.cider.mx/cider/contributing/hacking.html

2022-07-25 16:10 UTC, bbatsov commented
@dgutov Can you take a look at the proposed changes as an expert in the API in question?

2022-07-25 16:12 UTC, bbatsov commented on cider-completion.el
> +            :exclusive 'no))))
What does this property mean?

2022-07-25 16:12 UTC, bbatsov commented on CHANGELOG.md
> +
Please kill the blank line.

2022-07-25 16:18 UTC, toniz4 commented on cider-completion.el
> +            :exclusive 'no))))
as stated in https://www.gnu.org/software/emacs/manual/html_node/elisp/Completion-in-Buffers.html

> :exclusive If the value is no, then if the completion table fails to match the text at point, completion-at-point moves on to the next function in completion-at-point-functions instead of reporting a completion failure.

2022-07-25 16:27 UTC, dgutov commented on cider-completion.el
> +            :exclusive 'no))))
I'm going to quote a smart person here:

>  Better stay far away from ":exclusive 'no".
> It's an ugly hack that's fundamentally broken (not just in its implementation).

https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00814.html

2022-07-25 16:30 UTC, dgutov commented
The `meta -> (categiry . cider)` part seems sound.

Though I don't know if it's a good idea to create a category per completion source. Perhaps @minad or @monnier have some opinion.

2022-07-25 16:46 UTC, toniz4 commented on cider-completion.el
> +              (cond ((eq action 'metadata) `(metadata (category . cider)))
As the docs says, the completion function should accept 3 args, one of them being a flag describing the complete operation, and that can have some values described at https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html

In the implementation in master, when action is `'metadata` or `'boundaries` it evaluates to `nil`, and when action is `nil`, `t` or `lambda`, action is passed to `(complete-with-action)`.

2022-07-25 16:53 UTC, toniz4 commented on cider-completion.el
> +            :exclusive 'no))))
Fair enough, it was working well without :exclusive 'no either way.

2022-07-25 17:00 UTC, monnier commented
Dmitry Gutov [2022-07-25 09:30:16] wrote:
> The `meta -> (categiry . cider)` part seems sound.

[ Assuming it really says `category` instead.  ]

> Though I don't know if it's a good idea to create a category per completion
> source.  Perhaps @minad or @monnier have some opinion.

The completion source is probably not a good choice of "category" since
the category should describe the kind of things that are completed
rather than how we found those things.

But I can imagine sound reasons to want to pay attention to the "how",
e.g. because some completion styles work poorly with particular backends.

[ Reminds me that I suspect the notion of "category" will probably need to
  grow some kind of hierarchy (or something) at some point.  ]


        Stefan

2022-07-25 17:04 UTC, bbatsov commented
So can someone give me some examples of categories? I get this should be the implementation (e.g. CIDER), so what is it supposed to be?

2022-07-25 17:12 UTC, toniz4 commented
> So can someone give me some examples of categories? I get this should be the implementation (e.g. CIDER), so what is it supposed to be?

you can see that with describe-variable completion-category-defaults, by default it comes pre-populated with some categories.

I agree with @monnier, but this is the only way that i know to get a finer control of the completion style, i.e. only apply a specific style for completions comming from cider.

Eglot and lsp-mode follows the same idea:

https://github.com/emacs-lsp/lsp-mode/blob/b2dc84128fc6b2cd0460569bae6d0451856d2e0b/lsp-completion.el#L514

https://github.com/joaotavora/eglot/blob/6cc6fcc0fabb51671980e52110ad74f2e691e387/eglot.el#L2613

Eglot sets the category as eglot, and lsp-mode sets it to lsp-capf

2022-07-25 19:56 UTC, bbatsov commented on cider-completion.el
> +            (lambda (string pred action)
I think `prefix` is a better name then `string` here.

2022-07-25 19:57 UTC, bbatsov commented on cider-completion.el
> +              (cond ((eq action 'metadata) `(metadata (category . cider))) ; metadata
Here I meant some high-level comment explaining the completion API. :-) The current comments don't really explain anything for someone who doesn't know what this lambda is supposed to return.

2022-07-25 19:58 UTC, bbatsov commented
Fair enough. It'd be good if you also added something in the completion docs for `(setq completion-category-defaults '((cider (styles basic)))`.

2022-07-25 20:53 UTC, minad commented on cider-completion.el
> +            :exclusive 'no))))
I am not as smart as @monnier, but I disagree with him that :exclusive=no is fundamentally broken. The implementation in minibuffer.el is fundamentally broken, the substitute in corfu.el is not. I also claim that there is value in :exclusive=no even if merging of Capfs or completion tables may be preferable in many scenarios.

Anyway there is an easy solution - just declare all the Capf properties as a separate variable, which can be adjusted by the user. See:

https://github.com/minad/cape/blob/main/cape.el#L235-L239
https://github.com/minad/cape/blob/ad13cc9e3a505fc3fa56ac559d15e3eca7bcc731/cape.el#L268

2022-07-25 20:54 UTC, toniz4 commented on cider-completion.el
> +              (cond ((eq action 'metadata) `(metadata (category . cider))) ; metadata
The current explanation seems more appropriate? Be aware that english is my second language, so grammar mistakes are bound to happen.

2022-07-25 20:57 UTC, minad commented
@toniz4 Since you touch the completion code here, it would be great if #3006 could be addressed too, such that the default cider completion style becomes more compliant.

2022-07-25 21:08 UTC, toniz4 commented
> @toniz4 Since you touch the completion code here, it would be great if #3006 could be addressed too, such that the default cider completion style becomes more compliant.

Yes, I opened this PR following that rabbit role, but I think I will try to adress that problem in another PR. I will have to understand how the cider completion works in a deeper level.

The interesting thing that I found is that the builtin emacs funcions for building capf's are kinda non-complient, like (complete-with-action) or (completion-table-dynamic). Or i'm undersanding stuff wrong, documentation is rare about this stuff.

@minad Where do you find good documentation about capf's? Or the emacs manuals should be enought?

2022-07-25 21:14 UTC, minad commented
> The interesting thing that I found is that the builtin emacs funcions for building capf's are kinda non-complient, like (complete-with-action) or (completion-table-dynamic). Or i'm undersanding stuff wrong, documentation is rare about this stuff.

The limitation is that `completion-table-dynamic` requires you to use the `basic`, `emacs21` or `emacs22` completion styles such that the input string is passed to the completion table.

> Where do you find good documentation about capf's? Or the emacs manuals should be enought?

For Capfs the Emacs manual is not really a sufficient resource, but you can grep for example Capfs. My [Cape](https://github.com/minad/cape) package also comes with a bunch of simple Capfs you could use as reference.

I just looked at #3006 again. My recommendation is to remove the cider completion style completely:

https://github.com/clojure-emacs/cider/blob/b47fe53b39184b03b413284139d81b255d559db9/cider-completion.el#L281-L295

Instead configure the `basic` completion style for the `cider` category you introduced above.

2022-07-25 23:37 UTC, monnier commented
> I agree with @monnier, but this is the only way that i know to get a finer
> control of the completion style, i.e. only apply a specific style for
> completions comming from cider.

I'd need to know *why* you want the completion style to be different
when you use CIDER to be able to start thinking a bout what's
a better answer.

Is CIDER used only for one particular kind of completion (e.g. is it
only used to complete function names, or also file names, module names,
...)?

2022-07-26 03:05 UTC, toniz4 commented
> I agree with @monnier, but this is the only way that i know to get a finer control of the completion style, i.e. only apply a specific style for completions comming from cider.
> I'd need to know *why* you want the completion style to be different when you use CIDER to be able to start thinking a bout what's a better answer. Is CIDER used only for one particular kind of completion (e.g. is it only used to complete function names, or also file names, module names, ...)?

 I use orderless as the completion style globaly, and I would like to keep it that way for most of the capf's, but some capf's don't play nicely with that, as #3006 shows. And it's nice to have the option to set a different completion style in this category, orderless gives you the option of making custom completion engines.
 
 I could set `completion-styles` to `basic` localy when using cider, but every other completion will use `basic` too, if not overwriten in `completion-category-defaults` or `completion-category-overrides`, so it would fix one part and break the rest.

2022-07-26 06:57 UTC, minad commented
Using a completion category here is valid. But you could also set globally:

~~~ elisp
(setq completion-styles '(orderless basic)
~~~

This is the recommended configuration from the Orderless configuration and will make sure that completion-table-dynamic works properly.

2022-07-26 13:37 UTC, toniz4 commented on cider-completion.el
> +              (cond ((eq action 'metadata) `(metadata (category . cider))) ; metadata
So how is the current comments looking?

2022-07-26 14:25 UTC, bbatsov commented on cider-completion.el
> +              (cond ((eq action 'metadata) `(metadata (category . cider))) ; metadata
It's fine.

2022-07-26 20:20 UTC, bbatsov commented on doc/modules/ROOT/pages/usage/code_completion.adoc
> +`completion-category-defaults`, overriting the completion style just for the cider
overriding
cider -> CIDER.

2022-07-26 20:21 UTC, bbatsov requested changes

2022-07-26 20:21 UTC, bbatsov commented on doc/modules/ROOT/pages/usage/code_completion.adoc
> +Sometimes there will be problems displaying completions when using a different value in
That is a bit vague. Perhaps this shouldn't framed in terms of problems (this can go in the troubleshooting section), but in terms of what's the benefit of changing the default completion style in the first place.

2022-07-27 17:19 UTC, toniz4 commented on doc/modules/ROOT/pages/usage/code_completion.adoc
> +Sometimes there will be problems displaying completions when using a different value in
Updated it, how is it now?

2022-07-28 05:06 UTC, bbatsov commented on doc/modules/ROOT/pages/usage/code_completion.adoc
> +Sometimes there will be problems displaying completions when using a different value in
It's okay.

2022-07-28 05:08 UTC, merged

2022-10-11 08:17 UTC, monnier commented
> The interesting thing that I found is that the builtin emacs funcions for
> building capf's are kinda non-complient, like (complete-with-action) or
> (completion-table-dynamic). Or i'm undersanding stuff wrong, documentation
> is rare about this stuff.

These don't build "capf"s, they build completion tables.

   CAPF =  () -> (POS POS COMPLETION-TABLE)


-- Stefan