[inspector] Add configuration for max-nested-depth and spacious
clojure-emacs/cider pull request #3664
Opened 2024-05-13 21:20 UTC by alexander-yakushev

The PR doesn't depend on `cider-nrepl` being the latest version, but a release of it would be appreciated before merging. CIDER versions in the customs are approximated.

2024-05-13 21:38 UTC, vemv commented
Looks good. A cider-nrepl artifact is being built. I'll bump it here then

(please don't merge this before that)

2024-05-13 23:01 UTC, vemv commented
Done, you can merge master in

2024-05-14 06:57 UTC, alexander-yakushev commented
Thank you! I added a CHANGELOG commit, or is that unnecessary?

2024-05-14 07:23 UTC, bbatsov commented on cider-inspector.el
> +  :package-version '(cider . "1.2.0"))
Same here.

2024-05-14 07:26 UTC, alexander-yakushev commented
I changed `cider-inspector-spacious-collections` from a `defcustom` to a `defvar`. It is very likely that we will remove this option soon (we only add it as a fallback and to gauge if anybody cares enough about reverting it to the old mode). With `defvar` I think there will be smaller chance of this customization lingering in people's configs, and we won't have to keep it for backward compatibility.

2024-05-14 07:29 UTC, bbatsov commented
Fair enough. I asked about this before seeing your comment.

I'd suggest to mention the changes in this PR in the changelog as well and it'd be good if the new defcustom is also mentioned in the inspector's docs, so more people would actually discover it.

2024-05-17 07:08 UTC, alexander-yakushev commented
Ping 🙂

2024-05-17 07:47 UTC, bbatsov commented
@alexander-yakushev Did you see my previous small remarks? I see there no changes after writing them (e.g. the incorrect CIDER version in one defcustom)

2024-05-17 07:57 UTC, alexander-yakushev commented
Yep, I addressed them right after.
<img width="911" alt="image" src="https://github.com/clojure-emacs/cider/assets/468477/1ab2d5e3-633d-46ce-a183-da9200ad0c30">

2024-05-17 08:10 UTC, bbatsov requested changes

2024-05-17 08:10 UTC, bbatsov commented
Hmm, perhaps I didn't press the button "finish review" then. 😅

2024-05-17 08:19 UTC, alexander-yakushev commented on doc/modules/ROOT/pages/debugging/inspector.adoc
> +| kbd:[C]
I chose a capital letter intentionally to not take away a letter from the binding space. I don't consider this customization to be used often or ever. We'll probably change the default some time down the road and leave the customization for some unique cases, but otherwise, it's a meh variable to customize.

2024-05-17 08:47 UTC, bbatsov commented on doc/modules/ROOT/pages/debugging/inspector.adoc
> +| kbd:[C]
Fair enough.

2024-05-17 08:48 UTC, merged

2024-05-17 08:48 UTC, bbatsov commented
Thanks and sorry about the delay here!